# handle-io circleci configuration file

version: 2
jobs:
  install:
    docker:
      - image: circleci/node:9
    filters:
      branches:
        ignore: gh-pages
    steps:
      - checkout
      - restore_cache:
          keys:
          - handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

      # install
      - run: npm install

      # update lockfile
      - run: npx greenkeeper-lockfile-update

      # fix lockfile
      - run: npm install

      # upload lockfile
      - run: npx greenkeeper-lockfile-upload

      - save_cache:
          paths:
            - node_modules
            - package-lock.json
          key: handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

  build:
    docker:
      - image: circleci/node:9
    filters:
      branches:
        ignore: gh-pages
    steps:
      - checkout
      - restore-cache:
          keys:
            - handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

      # run build
      - run: npm run build

      - store_artifacts:
          path: ./dist
      - store_artifacts:
          path: ./lib
      - store_artifacts:
          path: ./es

  unit_test:
    docker:
      - image: circleci/node:9
    filters:
      branches:
        ignore: gh-pages
    steps:
      - checkout
      - restore-cache:
          keys:
            - handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

      # run test
      - run: npm run test

  code_coverage:
    docker:
      - image: circleci/node:9
    filters:
      branches:
        ignore: gh-pages
    steps:
      - checkout
      - restore-cache:
          keys:
            - handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

      # run test:coverage
      - run: npm run test:coverage

      # run codecov
      - run: npx codecov


  style_test:
    docker:
      - image: circleci/node:9
    filters:
      branches:
        ignore: gh-pages
    steps:
      - checkout
      - restore-cache:
          keys:
            - handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

      # run lint
      - run: npm run lint

  node6_bundle_test:
    docker:
      - image: circleci/node:6
    filters:
      branches:
        ignore: gh-pages

    steps:
      - checkout
      - restore_cache:
          keys:
          - handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

      # run test:bundle
      - run: npm run test:bundle


  node7_bundle_test:
    docker:
      - image: circleci/node:7
    filters:
      branches:
        ignore: gh-pages

    steps:
      - checkout
      - restore_cache:
          keys:
          - handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

      # run test:bundle
      - run: npm run test:bundle


  node8_bundle_test:
    docker:
      - image: circleci/node:8
    filters:
      branches:
        ignore: gh-pages

    steps:
      - checkout
      - restore_cache:
          keys:
          - handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

      # run test:bundle
      - run: npm run test:bundle


  node9_bundle_test:
    docker:
      - image: circleci/node:9
    filters:
      branches:
        ignore: gh-pages

    steps:
      - checkout
      - restore_cache:
          keys:
          - handle-io-dependencies-node9-{{ checksum "package-lock.json" }}

      # run test:bundle
      - run: npm run test:bundle


workflows:
  version: 2
  build_test:
    jobs:
      - install
      - unit_test:
          requires:
            - install

      - code_coverage:
          requires:
            - install

      - style_test:
          requires:
            - install

      - node6_bundle_test:
          requires:
            - install

      - node7_bundle_test:
          requires:
            - install

      - node8_bundle_test:
          requires:
            - install

      - node9_bundle_test:
          requires:
            - install

      - build:
          requires:
            - unit_test
            - code_coverage
            - style_test
            - node6_bundle_test
            - node7_bundle_test
            - node8_bundle_test
            - node9_bundle_test
