# handle-io circleci configuration file

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    filters:
      branches:
        ignore: gh-pages
    steps:
      - checkout
      - restore-cache:
          keys:
            - handle-io-dependencies-{{ checksum "package.json" }}

      # install latest npm version
      - run: sudo npm install -g npm@latest

      # install greenkeeper-lockfile
      - run: sudo npm install -g greenkeeper-lockfile@latest

      # update lockfile
      - run:
          command: npx greenkeeper-lockfile-update
          environment:
            GK_LOCK_COMMIT_AMEND: true

      # install
      - run: npm install

      - save_cache:
         paths:
            - node_modules
            - package-lock.json
         key: handle-io-dependencies-{{ checksum "package.json" }}

      # build
      - run: npm run build

      # lint
      - run: npm run lint

      # test
      - run: npm run test

      # integration test
      - run: npm run test:bundle

      # run test:coverage
      - run: npm run test:coverage

      # run codecov
      - run: npx codecov

      # upload lockfile
      - run:
          command: npx greenkeeper-lockfile-upload
          environment:
            GK_LOCK_COMMIT_AMEND: true

      - store_artifacts:
          path: ./dist
      - store_artifacts:
          path: ./lib
      - store_artifacts:
          path: ./es




  release:
    docker:
      - image: circleci/node:9
    filters:
      branches:
        ignore: gh-pages
    steps:
      - checkout
      - restore-cache:
          keys:
            - handle-io-dependencies-{{ checksum "package.json" }}

      # run semantic-release
      - run: npx semantic-release


workflows:
  version: 2
  build_test:
    jobs:
      - build
      - release:
          requires:
            - build